# Generated by Django 5.1.2 on 2024-10-30 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the pizza', max_length=100)),
                ('description', models.CharField(help_text='Enter the description of the pizza', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the pizza', max_digits=5)),
                ('size', models.CharField(help_text='Enter the size of the pizza (e.g., Small, Medium, Large)', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="Enter the employee's role", max_length=50)),
                ('phone_number', models.CharField(help_text="Enter the employee's phone number", max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Enter the member's phone number", max_length=15, null=True)),
                ('street_address', models.CharField(help_text="Enter the member's street address", max_length=50, null=True)),
                ('city', models.CharField(help_text='Enter the city', max_length=25, null=True)),
                ('state', models.CharField(help_text='Enter the state', max_length=20, null=True)),
                ('zip_code', models.CharField(help_text='Enter the postal code', max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='The date the order was placed')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the order', max_digits=10)),
                ('order_status', models.CharField(help_text='Status of the order (e.g., Pending, Completed)', max_length=50)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee who placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee')),
                ('guest', models.ForeignKey(blank=True, help_text='Guest who placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.guest')),
                ('member', models.ForeignKey(blank=True, help_text='Member who placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(help_text='Enter the card number', max_length=16)),
                ('expiration_date', models.CharField(help_text="Enter the card's expiration date (MM/YY)", max_length=5)),
                ('security_code', models.CharField(help_text="Enter the card's security code", max_length=3)),
                ('billing_zip_code', models.CharField(help_text='Enter the billing zip code', max_length=10)),
                ('order', models.ForeignKey(help_text='The order this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='catalog.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of pizzas ordered')),
                ('employee', models.ForeignKey(help_text='Employee who made the pizza', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee')),
                ('order', models.ForeignKey(help_text='The order this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='catalog.order')),
                ('pizza', models.ForeignKey(help_text='The pizza in this order', on_delete=django.db.models.deletion.CASCADE, to='catalog.pizza')),
            ],
        ),
    ]
